import AuthContextProvider from "@/context/AuthContext/AuthContextProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider/ReactQueryProvider";
import ThemeProvider from "@/providers/ThemeProvider/ThemeProvider";
import type { Metadata } from "next";
import AuthLayout from "./authLayout";
import "./globals.css";

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by NextJS and Spring MVC",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider>
          <ReactQueryProvider>
            <AuthContextProvider>
              <AuthLayout>{children}</AuthLayout>
            </AuthContextProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
